### ISSUE TITLE
[BUG] setting cli flags causes config file to be ignored 

### ISSUE THREAD

**Issue by myrddraall** [OpenAPITools/openapi-generator-cli#371]
# ⚠️ Important Notice

### Please differentiate the bug

This repository is not responsible for the actual code generation. If you have problems with the code generation, please open the bug at [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator). 

Please also check if the bug is already known before you open a new bug.

----------------------------------------------------------------------------

# 🐛 Bug Report:

### Describe the bug

you cant seem to mix a config file with some of the cli options.
In this case I'm trying to set --server-variables=major=2 as the version is determined via script

#### Config File:
```
{
  "$schema": "../../node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.1.1",
    "generators": {
      "server": {
        "generatorName": "aspnetcore",
        "output": "#{cwd}/../.generated",
        "glob": "src/*.{json,yaml,yml}",
        "modelNameSuffix": "",
        "apiNameSuffix": "Base",
        "additionalProperties": {
          "aspnetCoreVersion": "5.0",
          "classModifier": "abstract",
          "buildTarget": "library",
          "isLibrary": true,
          "packageName": "OpenApi.Generated",
          "operationIsAsync": true,
          "operationResultTask": true,
          "operationModifier": "abstract",
          "swashbuckleVersion": "5.0.0"
        }
      }
    }
  }
}

```

running `openapi-generator-cli generate` woks as expected

running `openapi-generator-cli generate --server-variables=major=2` errors with:
`[error] Required option '-i' is missing`

running `openapi-generator-cli generate --server-variables=major=2 --config=openapitools.json` errors with:

```
Exception in thread "main" java.lang.NullPointerException: generator name must be specified
        at org.apache.commons.lang3.Validate.notEmpty(Validate.java:395)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:482)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

### Expected behavior
The cli should use the settings in the config file, with any cli arguments added/overriding the values in the file

### Operation System (please complete the following information):
 - OS:  Ubuntu
 - Version 20

### Package System (please complete the following information):
 - npm 6.14.13
.

**Comment by LeonBlade** [comment]
I'm having this issue as well. I'd like to be able to override the JSON with my own parameters.

**Comment by catadnl** [comment]
Facing the same issue. Did anyone fin a workaround for this?

**Comment by chancesmith** [comment]
same here

**Comment by kareem-abdul** [comment]
same here. any updates for this?

**Comment by hannanstd** [comment]
same issue

**Comment by storyd** [comment]
was this resolved or is this utility under supported?

**Comment by aeoncl** [comment]
same issue
