### ISSUE TITLE
RuntimeException: Could not generate model 'AddressBodySchema'

### ISSUE THREAD

**Issue by InoMurko** [OpenAPITools/openapi-generator-cli#38]
Hello!

So I'm running:
```
docker run --rm     --user $(id -u):$(id -g)     openapitools/openapi-generator-cli:v4.3.0 validate     -i https://raw.githubusercontent.com/omgnetwork/elixir-omg/master/apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml
Validating spec (https://raw.githubusercontent.com/omgnetwork/elixir-omg/master/apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml)
No validation issues detected.
```

```
docker run --rm     --user $(id -u):$(id -g)     openapitools/openapi-generator-cli:v4.3.0 generate     -i https://raw.githubusercontent.com/omgnetwork/elixir-omg/master/apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml     -g elixir     -o apps/watcher_security_critical_api/
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: elixir (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'elixir' is considered stable.
[main] INFO  o.o.codegen.AbstractGenerator - writing file /apps/watcher_security_critical_api/lib/watcher_security_critical_api/model/address_body_schema.ex
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'AddressBodySchema'
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:539)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1005)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:426)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.nio.file.NoSuchFileException: /apps/watcher_security_critical_api/lib/watcher_security_critical_api/model/address_body_schema.ex
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at org.openapitools.codegen.AbstractGenerator.writeToFileRaw(AbstractGenerator.java:111)
	at org.openapitools.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:96)
	at org.openapitools.codegen.DefaultGenerator.writeToFile(DefaultGenerator.java:1513)
	at org.openapitools.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:57)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1080)
	at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:384)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:530)
	... 3 more
```

The stacktrace isn't very informative. Any hints how to debug this? Could this be an issue with the CLI?

**Comment by InoMurko** [comment]
Ah, for future reference... I forgot to mount the output dir:
```
-v ${PWD}/apps:/apps


docker run --rm  -v ${PWD}/apps:/apps   --user $(id -u):$(id -g)     openapitools/openapi-generator-cli:v4.2.3 generate     -i https://raw.githubusercontent.com/omgnetwork/elixir-omg/master/apps/omg_watcher_rpc/priv/swagger/security_critical_api_specs.yaml     -g elixir     -o apps/watcher_security_critical_api/
```
