### ISSUE TITLE
Unable to execute openapi-generator-cli version[BUG]

### ISSUE THREAD

**Issue by ralphflat** [OpenAPITools/openapi-generator-cli#390]
Using version 2.3.5 of openapi-generator-cli in the Node environment.  I am getting the error shown below.  Googling, I found bug #130 in this issue database.  this report seems to imply that proxy settings might be the problem.  Investigating now how to deal with specifying the proxies.

[rflatau@localhost server]$ npx @openapitools/openapi-generator-cli version
Unable to query repository, because of: "Request failed with status code 501"

Response:
server squid/3.4.8
mime-version 1.0
date Tue, 22 Jun 2021 13:39:33 GMT
content-type text/html
content-length 3484
x-squid-error ERR_UNSUP_REQ 0
vary Accept-Language
content-language en
x-cache MISS from intergate2
x-cache-lookup NONE from intergate2:3132
via 1.1 intergate2 (squid/3.4.8)
connection close

(node:35812) UnhandledPromiseRejectionWarning: TypeError: error.response.data.on is not a function
    at VersionManagerService.printResponseError (/home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:922:33)
    at /home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:828:18
    at /home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:46
    at OperatorSubscriber._this._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:38:21)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:35812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davesargrad** [comment]
@ralphflat 

I have this same problem. Thank you for taking the time to post this issue.

**Comment by davesargrad** [comment]
@ralphflat 

I'm assuming that you can run with a command such as this:

npx @openapitools/openapi-generator-cli -c cfg.json version

Where cfg.json is the file containing the json data that specifies the download URL

**Comment by ralphflat** [comment]
I have tried the suggestion from @davesargrad  above and get the following results (seems to be the same as original comment). 
 I also tried to use the help option on the command line with no result beyond an error very similar to below.

@kay-schecker please provide some guidance, as I am out of ideas as to what to try.

`[rflatau@localhost server]$ npx @openapitools/openapi-generator-cli -c cfg.json version
Unable to query repository, because of: "Request failed with status code 501"

Response:
server squid/3.4.8
mime-version 1.0
date Tue, 22 Jun 2021 14:50:57 GMT
content-type text/html
content-length 3484
x-squid-error ERR_UNSUP_REQ 0
vary Accept-Language
content-language en
x-cache MISS from intergate2
x-cache-lookup NONE from intergate2:3132
via 1.1 intergate2 (squid/3.4.8)
connection close

(node:37076) UnhandledPromiseRejectionWarning: TypeError: error.response.data.on is not a function
    at VersionManagerService.printResponseError (/home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:922:33)
    at /home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:828:18
    at /home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:46
    at OperatorSubscriber._this._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:38:21)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:37076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by davesargrad** [comment]
@ralphflat 

Actually you may need to simply edit openapitools.json as seen [here](https://github.com/OpenAPITools/openapi-generator-cli).

**Comment by ralphflat** [comment]
Following the suggestion, I edited the openapitools.json, per @davesargrad's suggestion, and did not have the -c on the command line.  The results are below.

```
[rflatau@localhost server]$ npx @openapitools/openapi-generator-cli version
Unable to query repository, because of: "Request failed with status code 501"

Response:
server squid/3.4.8
mime-version 1.0
date Tue, 22 Jun 2021 15:06:56 GMT
content-type text/html
content-length 3484
x-squid-error ERR_UNSUP_REQ 0
vary Accept-Language
content-language en
x-cache MISS from intergate2
x-cache-lookup NONE from intergate2:3132
via 1.1 intergate2 (squid/3.4.8)
connection close

(node:37312) UnhandledPromiseRejectionWarning: TypeError: error.response.data.on is not a function
    at VersionManagerService.printResponseError (/home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:922:33)
    at /home/rflatau/devel/learning_center-main/api/node_modules/@openapitools/openapi-generator-cli/main.js:828:18
    at /home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:46
    at OperatorSubscriber._this._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:38:21)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
    at OperatorSubscriber.Subscriber.error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:18)
    at OperatorSubscriber.Subscriber._error (/home/rflatau/devel/learning_center-main/api/node_modules/rxjs/dist/cjs/internal/Subscriber.js:104:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:37312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

openapitools.json contained the following information:

```
[rflatau@localhost server]$ more openapitools.json
{
  "$schema"" "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.1.1"
}
```

**Comment by davesargrad** [comment]
@ralphflat 

Looks like you are now hitting a squid proxy properly.. It seems to be rejecting your request to download from maven.

**Comment by ralphflat** [comment]
I got some feedback from IT group monitoring the internet activity.  The failed command above got the following error:  

`1624375550.827      0 10.92.82.143 TAG_NONE/501 3805 GET https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.1/openapi-generator-cli-5.1.1.jar?test123 - HIER_NONE/- text/html`

**Comment by davesargrad** [comment]
@ralphflat 

Until we get some guidance from @kay-schecker, I think perhaps you should try the openapi generator.. and bypass the openapi-generator-cli command line wrapper.

**Comment by kay-schecker** [comment]
Hi sorry for the late response. It's very difficult to debug such issues, because proxies often produce strange errors. I just found this article: https://stackoverflow.com/questions/27636360/squid-proxy-gives-501-on-get-request-made-by-python-but-not-curl

Could you try to create a short node.js script (using axios) to debug this issue within your network?

**Comment by davesargrad** [comment]
Hi @kay-schecker 

I'll be glad to push that issue to our IT guys. Perhaps indeed it is in the configuration of the squid proxy. Good find.

**Comment by ralphflat** [comment]
@kay-schecker 

I asked our IT guy about this and he provided the following:  "The web page referenced is correct that you cannot simply open a tcp connection to the proxy server and issue a GET command.  For https sites you will have to use the proxy CONNECT method, and then you will have to negotiate TLS, and then you can issue your http GET command."

**Comment by Zialus** [comment]
Sorry to repost my [request](https://github.com/OpenAPITools/openapi-generator-cli/issues/130#issuecomment-749115467) here, but seems like it was ignored last time and I've been using some workarounds in the meantime, such as _unsetting_ the env var manually + using a private nexus repository. But I'd still like to know if it would be possible to add the ability to respect the NO_PROXY env variable.

**Comment by pstanoev** [comment]
I am having similar issue. It is most likely that the NO_PROXY environment variable is not respected.

**Comment by naris** [comment]
I have a similar issue. I am completely unable to run openapi-generator-cli at all. Although I always get a 400 error instead of a 501. I am also behind a corporate proxy using windows 10. I haev the proxy setup in windows and npm and everything else, other than openapi-genereator-cli has no issues :(

`╰─ npx @openapitools/openapi-generator-cli version                                                                                      ─╯ 
Unable to query repository, because of: "Request failed with status code 400"

Response:
cache-control no-cache
pragma no-cache
content-type text/html; charset=utf-8
proxy-connection close
connection close
content-length 513

(node:23516) UnhandledPromiseRejectionWarning: TypeError: error.response.data.on is not a function
    at VersionManagerService.printResponseError (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\main.js:958:33)
    at C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\main.js:864:18
    at C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\operators\catchError.js:13:46 
    at OperatorSubscriber._this._error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:38:21)
    at OperatorSubscriber.Subscriber.error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\Subscriber.js:81:18)
    at SafeSubscriber.__tryOrUnsub (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:72:18)
    at OperatorSubscriber.Subscriber._error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\Subscriber.js:105:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by naris** [comment]
If I disconnect my corporate VPN connection and remove the proxy setting I get this instead:
`╰─ npx @openapitools/openapi-generator-cli version                                                                   ─╯
Unable to query repository, because of: "unable to get local issuer certificate"

Response:
(node:27980) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headers' of undefined
    at VersionManagerService.printResponseError (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\main.js:956:43)
    at C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\main.js:864:18
    at C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\operators\catchError.js:13:46
    at OperatorSubscriber._this._error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:38:21)
    at OperatorSubscriber.Subscriber.error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\Subscriber.js:81:18)
    at SafeSubscriber.__tryOrUnsub (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\src\metadater\node_modules\rxjs\internal\Subscriber.js:72:18)
    at OperatorSubscriber.Subscriber._error (C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\node_modules\rxjs\dist\cjs\internal\Subscriber.js:105:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by naris** [comment]
I managed to work around the issue by installing and using an old version:
npm install @openapitools/openapi-generator-cli@cli-3.2.0

**Comment by naris** [comment]
or not. That version throws an error :(
`internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\src\metadater\node_modules\@openapitools\openapi-generator-cli\main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by naris** [comment]
Unfortunately the cli-3.2.0 version of the generator generates code for Angular 4.3 which is not usable with a more current version of angular :(

**Comment by rdelhommer** [comment]
I was also able to find a workaround for this by manually setting the version in my openapitools.json file. The issue is happening when the npm wrapper tries to query the lastest available version of openapi-generator from maven.  If you've set your version in openapitools.json, it wont run the query and will just download the jar file  corresponding to the version you've chosen.  So far I haven't had any issues with downloading the jar.  Really only the query seems to be having issues

Example
```
"version": "5.2.1"
```

**Comment by JohannesHoppe** [comment]
I looked a bit at the source code to find out how the proxy settings are used. 

This is the place where it happens:
https://github.com/OpenAPITools/openapi-generator-cli/blob/0645163a72244dc1d0ec8e07481b527c24439d88/apps/generator-cli/src/app/app.module.ts#L11
(see fix #130 & PR #139)

The environment variables HTTPS_PROXY and HTTP_PROXY are considered.
But as @pstanoev already assumed, the NO_PROXY environment variable is not respected. This must be taken into account and, if necessary, the environment variables must be set or removed accordingly.

**Comment by tapan-p** [comment]
Meanwhile, I was able to generate the client using below steps. Basically skipping the wrapper and accessing jar directly.
1. Download jar file with latest version from repository URL. (```https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/```)
2. Run below command to generate the package (assuming you have java installed, json file for spec downloaded locally and jar file is downloaded). 
   `java -jar openapi-generator-cli-5.3.1.jar generate -g csharp-netcore -i project.swagger.json -o ./Generated --skip-validate-spec`

**Comment by mwiede** [comment]
As per yarnpkg/yarn#841 setting `NODE_EXTRA_CA_CERTS` fixed it for me.
I had already set `cafile` in .npmrc, but it seems this was ignored.

**Comment by artmotion** [comment]
I kinda still have this problem (and also being behind a very restrictive corp proxy).
I even put the 6.6.0.jar into the folder AND *hoped* for to just continue to generate the client, but it still tries to access the internet an returns with:
```
npx openapi-generator-cli generate 
Unable to query repository, because of: "connect ETIMEDOUT 34.238.74.221:443"
```
which is basically always an IP that points to AWS, which probably hosts the maven repo.

I also tried to specify an in-house maven repo, that has the file already, but it looks like the configuration is *ignored* or *not picked up*.

Is there anyway I can further debug this or set something like "DO_NOT_DOWNLOAD=true" to resolve this.
(Other than that, I will now download the jar with PowerShell and call the jar file with Java directly to generate the client).
