### ISSUE TITLE
[BUG] java: Permission denied

### ISSUE THREAD

**Issue by andzno1** [OpenAPITools/openapi-generator-cli#460]
# 🐛 Bug Report:

### Describe the bug
When executing `openapi-generator-cli` after a fresh install I get the following error:
```Shell
(node:2879) UnhandledPromiseRejectionWarning: Error: /bin/sh: 1: java: Permission denied

    at <redacted>/node_modules/@openapitools/openapi-generator-cli/main.js:636:32
    at ChildProcess.exithandler (child_process.js:326:5)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:375:28)
    at Pipe.<anonymous> (net.js:675:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2879) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2879) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce
1. Install `openapi-generator-cli` via
```Shell
yarn add --dev @openapitools/openapi-generator-cli
```
2. Execute
```Shell
yarn run openapi-generator-cli help
```

### Expected behavior
The [help output](https://openapi-generator.tech/docs/usage#help) is being printed.

### Actual behavior
Abovementioned error is being displayed. In addition a file `openapitools.json` is being created:
```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.2.1"
  }
}
```

### Operation System
 - OS: WSL 2, Ubuntu 20.04

**Comment by andzno1** [comment]
I just realized that I didn't have java installed.
