### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fzdfy** [OpenAPITools/openapi-generator-cli#705]
network response:
{"code":"","message":"","current":1,"data":null,"pageSize":20,"success":true,"total":0}
response data is null, Report an error

Uncaught (in promise) Error: TypeError: Cannot read properties of null (reading 'map')
    at _callee$ (useFetchData.js:194:19)
    at tryCatch (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.throw (regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:23)
    at _throw (asyncToGenerator.js:25:9)

env:
react 
"@openapitools/openapi-generator-cli": "^2.6.0"

**Comment by wing328** [comment]
please open an issue in https://github.com/openAPITools/openapi-generator instead
