### ISSUE TITLE
[BUG] Unable to query repository becasuse of: "Socket connection timeout" in MacOS

### ISSUE THREAD

**Issue by abhijit-hota** [OpenAPITools/openapi-generator-cli#707]
# 🐛 Bug Report:

### Describe the bug
Generating in MacOS gives the following error:

```sh
Unable to query repository, because of: "Socket connection timeout"

Response:
/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/main.js:1034
            Object.entries(error.response.headers).forEach(a => this.logger.log(...a));
                                          ^

TypeError: Cannot read properties of undefined (reading 'headers')
    at VersionManagerService.printResponseError (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/main.js:1034:43)
    at /opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/main.js:915:18
    at /opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
    at OperatorSubscriber._this._error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at Subscriber.error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/opt/homebrew/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
```

### Operation System (please complete the following information):
 - OS: MacOS Ventura 13.4

### Package System (please complete the following information):
 - Version 6.4.0
 
### Additional context
It works somehow in Linux.

**Comment by luke-lacroix-healthy** [comment]
I'm getting a very similar issue:
```
> npm i -g @openapitools/openapi-generator-cli
> openapi-generator-cli --help
Unable to query repository, because of: "unable to get local issuer certificate"

Response:
/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/main.js:1034
            Object.entries(error.response.headers).forEach(a => this.logger.log(...a));
                                          ^

TypeError: Cannot read properties of undefined (reading 'headers')
    at VersionManagerService.printResponseError (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/main.js:1034:43)
    at /Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/main.js:915:18
    at /Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
    at OperatorSubscriber._this._error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at OperatorSubscriber.Subscriber.error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at OperatorSubscriber.Subscriber._error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at OperatorSubscriber.Subscriber.error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at OperatorSubscriber.Subscriber._error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at OperatorSubscriber.Subscriber.error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at OperatorSubscriber.Subscriber._error (/Users/lucas/.nvm/versions/node/v16.15.1/lib/node_modules/@openapitools/openapi-generator-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
```

**Comment by wing328** [comment]
please give it a try with the latest stable version 2.13.9

to completely bypass making a request to https://search.maven.org/, simply set the environment variable OPENAPI_GENERATOR_CLI_SEARCH_URL to DEFAULT, e.g. https://github.com/OpenAPITools/openapi-generator-cli/blob/master/.github/workflows/build.yml#L87
